"""Installation command for bash tab completion.

This module provides logic for installing bash completion for lw_coder CLI.
"""

from __future__ import annotations

import shutil
from pathlib import Path

from .logging_config import get_logger

logger = get_logger(__name__)


def check_argcomplete_installed() -> tuple[bool, str]:
    """Check if argcomplete is properly installed.

    Returns:
        Tuple of (is_installed, message).
    """
    # Check if register-python-argcomplete command is available
    if shutil.which("register-python-argcomplete") is None:
        return False, (
            "argcomplete is not installed or not in PATH.\n\n"
            "To install argcomplete:\n"
            "  Recommended: pipx install argcomplete\n"
            "  Alternative: pip install argcomplete  (or pip3)\n\n"
            "After installing, run 'lw_coder completion install' again."
        )
    return True, ""


def run_completion_install() -> int:
    """Install bash completion for lw_coder.

    This command:
    1. Creates ~/.bash_completion.d/ directory if needed
    2. Writes completion activation script
    3. Adds source line to ~/.bashrc if not present

    Returns:
        Exit code: 0 for success, 1 for failure.
    """
    home = Path.home()
    completion_dir = home / ".bash_completion.d"
    completion_script = completion_dir / "lw_coder"
    bashrc = home / ".bashrc"

    try:
        # Create completion directory
        completion_dir.mkdir(parents=True, exist_ok=True)
        logger.info("Created completion directory: %s", completion_dir)

        # Write completion script
        script_content = """# Bash completion for lw_coder CLI
# This file is auto-generated by 'lw_coder completion install'

# Register argcomplete for lw_coder
eval "$(register-python-argcomplete lw_coder)"
"""
        completion_script.write_text(script_content, encoding="utf-8")
        logger.info("Wrote completion script: %s", completion_script)

        # Check if bashrc sources the completion script
        source_line = f"[ -f {completion_script} ] && source {completion_script}\n"
        needs_source = True

        if bashrc.exists():
            bashrc_content = bashrc.read_text(encoding="utf-8")
            if str(completion_script) in bashrc_content:
                needs_source = False
                logger.info("Completion already configured in %s", bashrc)

        # Add source line to bashrc if needed
        if needs_source:
            with bashrc.open("a", encoding="utf-8") as f:
                f.write("\n# Source lw_coder bash completion\n")
                f.write(source_line)
            logger.info("Added completion source to %s", bashrc)

        # Check if argcomplete is installed
        argcomplete_ok, argcomplete_msg = check_argcomplete_installed()

        if not argcomplete_ok:
            print("\nCompletion script installed, but argcomplete is missing.")
            print()
            print(argcomplete_msg)
            return 1

        # Everything is set up correctly
        print("\nBash completion installed successfully!")
        print("\nTo activate, reload your shell:")
        print("  source ~/.bashrc")
        print("\nAfter that, tab completion will work with lw_coder commands.")

        return 0

    except (OSError, IOError) as exc:
        logger.error("Failed to install completion: %s", exc)
        return 1
