"""Pydantic models for training data types.

This module defines the data models used by the train command for
loading training samples, defining prompts, and generating candidates.
"""

from __future__ import annotations

from pydantic import BaseModel, Field


class TrainingSample(BaseModel):
    """A complete training sample from eval command.

    Each sample contains all artifacts generated during evaluation:
    - Plan content and identifier
    - Code trace from the implementation session
    - Human feedback on the quality of work
    - Judge results formatted as readable string
    - Test results before and after implementation
    """

    plan_id: str = Field(description="Unique identifier for the plan")
    plan_content: str = Field(description="Full content of the plan.md file")
    code_trace: str = Field(default="", description="Code trace from session (may be empty)")
    human_feedback: str = Field(description="Human feedback on the implementation")
    judge_results: str = Field(description="Formatted string of all judge scores/feedback")
    test_results_before: str = Field(default="", description="JSON string of before-test results")
    test_results_after: str = Field(description="JSON string of after-test results")


class SubagentDefinition(BaseModel):
    """Definition of a subagent for the coding workflow.

    Subagents are specialized helpers invoked by the main agent.
    Each has a name, description, and its own prompt.
    """

    name: str = Field(
        description="Kebab-case name, e.g., 'code-review-auditor'",
        min_length=1,
    )
    description: str = Field(
        description="Brief description for identification",
        min_length=1,
    )
    prompt: str = Field(
        description="Full markdown prompt content",
        min_length=1,
    )


class CurrentPrompts(BaseModel):
    """The current best prompts being improved upon.

    This represents the active prompt set that the train command
    will analyze and attempt to improve.
    """

    main_prompt: str = Field(description="Main system prompt content")
    subagents: list[SubagentDefinition] = Field(
        default_factory=list,
        description="List of subagent definitions",
    )


class CandidatePrompts(BaseModel):
    """Output: A new candidate prompt set.

    Generated by the DSPy prompt trainer based on training data analysis.
    """

    main_prompt: str = Field(description="Improved main prompt content")
    subagents: list[SubagentDefinition] = Field(
        default_factory=list,
        description="List of subagent definitions (up to max_subagents)",
    )
    analysis_summary: str = Field(
        description="Summary of what was learned and improved",
    )
