"""Integration tests verifying weft bwrap sandbox is operational.

This module tests that weft's custom bwrap sandbox provides filesystem isolation.
The distinction from previous Claude Code SDK sandbox tests is important:

**Architecture change**: Weft now uses its own bwrap-based sandbox instead of
relying on Claude Code's internal sandbox. This provides:
- Consistent behavior across SDK and CLI sessions
- Explicit control over mount paths via .weft/config.toml
- No dependency on socat (previously required by Claude Code sandbox)

**What this tests**: Verifies that bwrap correctly isolates the filesystem
by testing that the build_bwrap_command function produces a working sandbox
command that blocks writes to non-mounted paths.

Prerequisites:
- bubblewrap (bwrap) must be installed: sudo apt install bubblewrap
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

import pytest

from weft.sandbox import SandboxConfig, build_bwrap_command


def _require_bwrap() -> None:
    """Fail the test if bwrap is not installed."""
    if shutil.which("bwrap") is None:
        pytest.fail(
            "Required dependency 'bwrap' not found. "
            "Install with: sudo apt install bubblewrap"
        )


class TestBwrapSandboxOperational:
    """Tests verifying the bwrap sandbox is operational on this system."""

    def test_bwrap_sandbox_blocks_write_to_home_directory(self, tmp_path: Path) -> None:
        """Verify bwrap sandbox blocks file writes to user's home directory.

        This test verifies that the bwrap command generated by build_bwrap_command
        correctly blocks writes to paths not explicitly mounted.

        The home directory is not in the default mount list, so writes there
        should fail inside the sandbox.

        If this test fails:
        1. Verify bwrap is executable: which bwrap
        2. Check if you're running in a restricted environment (container, etc.)
        3. Re-run the test
        """
        _require_bwrap()

        # Create a worktree directory that will be mounted
        worktree = tmp_path / "worktree"
        worktree.mkdir()

        # Target file in home directory - should be blocked
        target_file = Path.home() / ".weft_sandbox_test_a9f3e2c1.tmp"
        unique_content = "weft_sandbox_verification_8b2f4a1c"

        # Clean up any leftover file from previous failed test run
        if target_file.exists():
            target_file.unlink()

        # Build a sandboxed command that tries to write to home directory
        config = SandboxConfig()  # Empty config - no extra mounts
        command = f"echo '{unique_content}' > {target_file}"
        bwrap_cmd = build_bwrap_command(command, config, worktree)

        try:
            # Run the sandboxed command (result unused - we check file existence instead)
            subprocess.run(
                bwrap_cmd,
                capture_output=True,
                text=True,
                timeout=30,
                check=False,
            )

            # The command should either fail with permission error or succeed
            # but the file should not exist outside the sandbox
            if target_file.exists():
                content = target_file.read_text().strip()
                if content == unique_content:
                    pytest.fail(
                        f"Sandbox is non-functional! File was written to {target_file}. "
                        f"This indicates bwrap sandbox is not working correctly. "
                        f"Check that bwrap is installed and working: sudo apt install bubblewrap"
                    )
                else:
                    pytest.fail(
                        f"Unexpected file content at {target_file}. "
                        f"Expected '{unique_content}', got '{content[:50]}...'. "
                        f"This suggests another process created this file."
                    )

            # File does not exist - sandbox successfully blocked the write
            # This is the expected behavior

        finally:
            # Cleanup in finally block guarantees no pollution even on assertion failure
            if target_file.exists():
                target_file.unlink()

    def test_bwrap_sandbox_allows_write_to_worktree(self, tmp_path: Path) -> None:
        """Verify bwrap sandbox allows writes to the mounted worktree.

        The worktree should be mounted read-write, so file creation
        inside it should succeed.
        """
        _require_bwrap()

        # Create a worktree directory that will be mounted
        worktree = tmp_path / "worktree"
        worktree.mkdir()

        # Target file inside worktree - should succeed
        target_file = worktree / "test_file.txt"
        unique_content = "sandbox_allows_worktree_write"

        # Build a sandboxed command that writes inside the worktree
        config = SandboxConfig()
        command = f"echo '{unique_content}' > {target_file}"
        bwrap_cmd = build_bwrap_command(command, config, worktree)

        # Run the sandboxed command
        result = subprocess.run(
            bwrap_cmd,
            capture_output=True,
            text=True,
            timeout=30,
            check=False,
        )

        # The file should exist with our content
        assert target_file.exists(), (
            f"File should exist at {target_file}. "
            f"stdout: {result.stdout}, stderr: {result.stderr}"
        )
        content = target_file.read_text().strip()
        assert content == unique_content, (
            f"File content mismatch. Expected '{unique_content}', got '{content}'"
        )

    def test_bwrap_sandbox_allows_write_to_configured_paths(self, tmp_path: Path) -> None:
        """Verify bwrap sandbox allows writes to paths configured in read_write_paths.

        Paths explicitly listed in SandboxConfig.read_write_paths should be
        accessible for writing.
        """
        _require_bwrap()

        # Create a worktree and an additional writable path
        worktree = tmp_path / "worktree"
        worktree.mkdir()
        extra_path = tmp_path / "extra_rw"
        extra_path.mkdir()

        # Target file in extra path - should succeed because it's in read_write_paths
        target_file = extra_path / "test_file.txt"
        unique_content = "sandbox_allows_configured_path"

        # Build a sandboxed command with extra path in read_write_paths
        config = SandboxConfig(read_write_paths=[str(extra_path)])
        command = f"echo '{unique_content}' > {target_file}"
        bwrap_cmd = build_bwrap_command(command, config, worktree)

        # Run the sandboxed command
        result = subprocess.run(
            bwrap_cmd,
            capture_output=True,
            text=True,
            timeout=30,
            check=False,
        )

        # The file should exist with our content
        assert target_file.exists(), (
            f"File should exist at {target_file}. "
            f"stdout: {result.stdout}, stderr: {result.stderr}"
        )
        content = target_file.read_text().strip()
        assert content == unique_content, (
            f"File content mismatch. Expected '{unique_content}', got '{content}'"
        )
