"""Pydantic models for training data types.

This module defines the data models used by the train command for
loading training samples, defining prompts, and generating candidates.
"""

from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field


class TrainingSample(BaseModel):
    """A complete training sample from eval command.

    Each sample contains all artifacts generated during evaluation:
    - Plan content and identifier
    - Code trace from the implementation session
    - Human feedback on the quality of work
    - Judge results formatted as readable string
    - Test results before and after implementation
    - Prompts used during the session (if available)
    - Metadata about tool, model, and fingerprints
    """

    plan_id: str = Field(description="Unique identifier for the plan")
    plan_content: str = Field(description="Full content of the plan.md file")
    code_trace: str = Field(default="", description="Code trace from session (may be empty)")
    human_feedback: str = Field(description="Human feedback on the implementation")
    judge_results: str = Field(description="Formatted string of all judge scores/feedback")
    test_results_before: str = Field(default="", description="JSON string of before-test results")
    test_results_after: str = Field(description="JSON string of after-test results")
    # New fields for metadata and prompts
    used_prompts: Optional["PromptSnapshot"] = Field(
        default=None, description="Prompts used during the session (if available)"
    )
    tool: str = Field(default="claude-code", description="Tool used (claude-code or droid)")
    model: Optional[str] = Field(default=None, description="Model used (sonnet, opus, haiku)")
    prompt_fingerprint: Optional[str] = Field(
        default=None, description="SHA256 fingerprint (8 chars) of prompts used"
    )
    eval_fingerprint: Optional[str] = Field(
        default=None, description="SHA256 fingerprint (8 chars) of judges used"
    )


class SubagentDefinition(BaseModel):
    """Definition of a subagent for the coding workflow.

    Subagents are specialized helpers invoked by the main agent.
    Each has a name, description, and its own prompt.
    """

    name: str = Field(
        description="Kebab-case name, e.g., 'code-review-auditor'",
        min_length=1,
    )
    description: str = Field(
        description="Brief description for identification",
        min_length=1,
    )
    prompt: str = Field(
        description="Full markdown prompt content",
        min_length=1,
    )


class PromptSnapshot(BaseModel):
    """A snapshot of prompts at a point in time.

    This model serves dual purposes:
    1. Representing the current best prompts being improved upon (for training)
    2. Recording the historical prompts used during a specific session
    """

    main_prompt: str = Field(description="Main system prompt content")
    subagents: list[SubagentDefinition] = Field(
        default_factory=list,
        description="List of subagent definitions",
    )


# Backwards compatibility alias
CurrentPrompts = PromptSnapshot


class SessionMetadata(BaseModel):
    """Metadata about a coding session.

    Recorded during `code` command execution and enhanced by `eval` command.
    """

    tool: str = Field(description="Tool used (claude-code or droid)")
    model: Optional[str] = Field(default=None, description="Model used (sonnet, opus, haiku)")
    recorded_at: datetime = Field(description="When the session was recorded (ISO format)")
    prompt_fingerprint: str = Field(
        description="SHA256 fingerprint (8 chars) of prompts used"
    )
    eval_fingerprint: Optional[str] = Field(
        default=None, description="SHA256 fingerprint (8 chars) of judges used (added by eval)"
    )


class CandidatePrompts(BaseModel):
    """Output: A new candidate prompt set.

    Generated by the DSPy prompt trainer based on training data analysis.
    """

    main_prompt: str = Field(description="Improved main prompt content")
    subagents: list[SubagentDefinition] = Field(
        default_factory=list,
        description="List of subagent definitions (up to max_subagents)",
    )
    analysis_summary: str = Field(
        description="Summary of what was learned and improved",
    )
